[stdlib]
minimum_version = "0.0.9"

[tasks.shell]
interactive = true
packages = ["base", "bash", "claude-code", "curl"]
exec = "bash --noprofile -l"

[tasks.claude]
interactive = true
packages = ["base", "bash", "claude-code", "curl"]
exec = "claude --dangerously-skip-permissions"
